### ISSUE TITLE
Module to manage ICF services

### ISSUE THREAD

**Issue by rainerleber** [ansible-collections/community.sap#18]
### Summary

A module to activate oder deactivate ICF services

### Issue Type

Feature Idea

### Component Name

sicf, pyrfc

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by jfilak** [comment]
We have an implemantation of this module with the following interface:

```yaml
module: community.sa.sap_sicf_service
short_description: This module controls ICF services
version_added: "2.4"
description:
    - "Activates/Deactivates the given SICF Service"
options:
    url:
        description:
            - Indentifies the ICF services
        required: true
    state:
        description:
            - sets the corresponding state
        choices: ['active', 'inactive']
        default: active
        required: false
```

Example
```yaml
- name: Test with a message
  sap_sicf_service:
  - url: "/sap/bc/ui2/flp"
    state: "active"
```
