### ISSUE TITLE
Module strust

### ISSUE THREAD

**Issue by rainerleber** [ansible-collections/community.sap#19]
### Summary

A module which manage certificates with strust

### Issue Type

Feature Idea

### Component Name

strust, pyrfc

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by jfilak** [comment]
We have an internal implementation of this module with the following interace:
```yaml
module: community.sap.sap_strust
short_description: This module imports SSL certificates
version_added: "?.?"
description:
    - "Import SSL certificates"
options:
    paths:
        description: list of paths to certificate files in X.509 Base64 format (PEM)
        type: list of str
        required: true
    storage:
        description: storge
        type: list of str
        required: false
        choices: (client_standart, client_anonymous)
    algorithm:
        description: R,S,G,H,X - or other if you need, of PSE file
        type: str
        required: false
    identity:
        description: Identity - TBC
        type: list of str
        required: false
    key_length:
        description: of PSE file
        type: int
        required: false
    dn:
        description: Distinguished Name of PSE file
        type: str
        required: false
```

Example:
```yaml
- name: Import SSL certificate
  community.sap.sap_strust:
    paths: /tmp/isrgrootx1.pem
    storage: client_anonymous
```

the module depends on https://github.com/jfilak/sapcli/

Are you interested accepting a patch?

PS: if you are wondering, then yes, we do have an internal collection called community.sap
