### ISSUE TITLE
/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found

### ISSUE THREAD

**Issue by dirktimmer** [ansible-collections/community.sap#26]
### Summary

Hi,

when I use the module hana_query, it isn't using the correct libstdc++.so.6. I modified the code and then it works.
I'm importing os: import os
The I put the following line, after the other two lines:
    if bin_path is None:
        bin_path = "/usr/sap/{sid}/HDB{instance}/exe/hdbsql".format(sid=sid.upper(), instance=instance)
        os.environ["LD_LIBRARY_PATH"] = "/usr/sap/{sid}/HDB{instance}/exe".format(sid=sid.upper(), instance=instance)

Then it works. I don't know how to handle this when bin_path is set, but I don't need it.

 

### Issue Type

Bug Report

### Component Name

Module: community.sap.hana_query

### Ansible Version

```config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Mar 18 2021, 08:58:41) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]```


### Community.sap Version

``` ansible-galaxy collection list community.sap don't work, but it is version 1.0.0
{
 "collection_info": {
  "namespace": "community",
  "name": "sap",
  "version": "1.0.0",
  "authors": [
   "Rainer Leber (github.com/rainerleber)",
   "Robert Kraemer (github.com/rkpobe)"
  ],
  "readme": "README.md",
  "tags": [
   "sap"
  ],
  "description": "SAP community collection for Ansible",
  "license": [],
  "license_file": "LICENSE",
  "dependencies": {},
  "repository": "https://github.com/ansible-collections/community.sap",
  "documentation": "https://github.com/ansible-collection/community.sap/tree/main/docs",
  "homepage": "https://github.com/ansible-collections/community.sap",
  "issues": "https://github.com/ansible-collections/community.sap/issues"
 },
 "file_manifest_file": {
  "name": "FILES.json",
  "ftype": "file",
  "chksum_type": "sha256",
  "chksum_sha256": "37274fcb06645cec88067238f9d976cb36d1a807453950618d6f8537de8483bc",
  "format": 1
 },
 "format": 1
}

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

RHEL 8

### Steps to Reproduce

any use of hana_query

### Expected Results

I expected that sql query worked with hdbsql

### Actual Results

```console (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by rainerleber** [comment]
Hi @dirktimmer thank for opening the issue we migrated the collection to a new organization: The new repository is here:
https://github.com/sap-linuxlab/community.sap_libs

**Comment by rainerleber** [comment]
I discover the problem from time to time. It's more a design decission to not implement this as you mentioned. But you could solve this by using the builtin environement function from ansible like this:

```
- hosts: all
  remote_user: root

  # create a variable named "proxy_env" that is a dictionary
  vars:
    hana_env:
      LD_LIBRARY_PATH: /usr/sap/hdb/HDB01/exe

  tasks:
    - name: Simple select query
      community.sap.hana_query:
        sid: "hdb"
        instance: "01"
        password: "Test123"
        query: select user_name from users
      environment: "{{ hana_env }}"
     
```
For more information have a look here:
https://docs.ansible.com/ansible/latest/user_guide/playbooks_environment.html

If you have further questions feel free to raise a new Issue at the new location.
