### ISSUE TITLE
Incorrect behaviour in case of nonexisting SAR file

### ISSUE THREAD

**Issue by machacekondra** [ansible-collections/community.sap#27]
### Summary

When you pass nonexisting sar file the module should exit with reasonable error message, rather then "already unpacked".

### Issue Type

Bug Report

### Component Name

sapcar_extract

### Ansible Version

```console (paste below)
$ ansible --version
2.12
```

### Community.sap Version

```console (paste below)
$ ansible-galaxy collection list community.sap

```
latest

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### Steps to Reproduce

```yaml (paste below)
- name: Unpack SAR files
  community.sap.sapcar_extract:
    path: "dontexists.sar"
    dest: "dontexists-extracted"
```

### Expected Results

Return code, so I know the file can't be extracted

### Actual Results

```console (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
